### PR TITLE
Add TSGM

### PR DESCRIPTION
**Pull request by AlexanderVNikitin**
Adding TSGM, a library for generative time series modeling and augmentations.

### CODE REVIEW

**Comment by lmmentel** [comment]
Thanks, would it possibly fit better under the [Time series augmentation](https://github.com/lmmentel/awesome-time-series?tab=readme-ov-file#time-series-augmentation) section?

**Comment by AlexanderVNikitin** [comment]
I thought about it, but TSGM use cases are broader than time series augmentation. It is also used to generate and evaluate synthetic time series data. Does it make sense to start a new section‚ e.g., "Generative Modeling" or "Synthetic Data Generation"?

**Comment by lmmentel** [comment]
How about a section named: "Time series generation and augmentation" ?

**Comment by AlexanderVNikitin** [comment]
Good point. I've added it to augmentations and renamed the section.

**Review by lmmentel — APPROVED** [review]
Thanks a lot! :raised_hands:

**Pull request merged**
